[project]
name = "ariston"
description = "ariston api"
long_description = "Python Ariston API"
version = "0.11"
authors = [
    { name = "Tamás Füstös", email = "fustom@gmail.com" }
]
dependencies = [
    "aiohttp",
]
requires-python = ">=3.9"
license = { file = "LICENSE" }

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
